# Используем образ RabbitMQ с management plugin
FROM rabbitmq:3.10.7-management

# Установка curl
RUN apt-get update && apt-get install -y curl

# Копируем скрипт и даем ему права на выполнение
COPY scripts/init-rabbitmq.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/init-rabbitmq.sh

# Устанавливаем команду по умолчанию для запуска RabbitMQ сервера
ENTRYPOINT ["/usr/local/bin/init-rabbitmq.sh"]

