env: local
server: "localhost:8080"
db:
  Host: localhost
  Port: "5432"
  DBName: NoteProject
  SSLMode: disable
  Delay: 5
  Attempts: 5
redis:
  Addr:     "localhost:6379"
  Password: "1234"
  DB:       0
