basePath: /
definitions:
  entities.Note:
    description: Note structure
    properties:
      date:
        type: string
      done:
        type: boolean
      id:
        type: integer
      text:
        type: string
      title:
        type: string
      user_id:
        type: integer
    required:
    - text
    - title
    - user_id
    type: object
  handler.Response:
    properties:
      Error:
        type: string
    type: object
  handler.inputNote:
    properties:
      text:
        type: string
      title:
        type: string
      user_id:
        type: integer
    type: object
  handler.userInput:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
host: localhost:8080
info:
  contact: {}
  description: API Server for notes workspace
  title: NoteProject
  version: "1.0"
paths:
  /auth/sign-in:
    post:
      consumes:
      - application/json
      description: Handles the request intended for logging into the application.
      parameters:
      - description: User data for login
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/handler.userInput'
      produces:
      - application/json
      responses:
        "200":
          description: Login successful
          schema:
            type: string
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/handler.Response'
        "401":
          description: Unauthorized access
          schema:
            $ref: '#/definitions/handler.Response'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/handler.Response'
      summary: signIn Log in to the app
      tags:
      - Auth
  /auth/sign-up:
    post:
      consumes:
      - application/json
      description: Handles the request to register a user in the application.
      parameters:
      - description: User data for creation
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/handler.userInput'
      produces:
      - application/json
      responses:
        "201":
          description: User ID
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/handler.Response'
        "409":
          description: 'Conflict: User already exists'
          schema:
            $ref: '#/definitions/handler.Response'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/handler.Response'
      summary: signUp User registration
      tags:
      - Auth
  /note/create:
    post:
      consumes:
      - application/json
      description: Handles the request to create a new note.
      parameters:
      - description: Data for creating a note
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/handler.inputNote'
      produces:
      - application/json
      responses:
        "201":
          description: Return id
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.Response'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/handler.Response'
      security:
      - ApiKeyAuth: []
      summary: Create a Note
      tags:
      - Notes
  /note/delete/{noteID}:
    delete:
      consumes:
      - application/json
      description: Handles the request to delete a note.
      parameters:
      - description: Note ID
        in: path
        name: noteID
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Successful response
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/handler.Response'
        "404":
          description: Note not found
          schema:
            $ref: '#/definitions/handler.Response'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/handler.Response'
      security:
      - ApiKeyAuth: []
      summary: Delete the note
      tags:
      - Notes
  /note/list/{userID}:
    get:
      consumes:
      - application/json
      description: Handles the request to display notes.
      parameters:
      - description: User ID
        in: path
        name: userID
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entities.Note'
            type: array
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/handler.Response'
        "404":
          description: Note not found
          schema:
            $ref: '#/definitions/handler.Response'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/handler.Response'
      security:
      - ApiKeyAuth: []
      summary: List Show users notes
      tags:
      - Notes
  /note/update:
    put:
      consumes:
      - application/json
      description: Handles the request to update a note.
      parameters:
      - description: Data for updating the note
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/entities.Note'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully updated note
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/handler.Response'
        "404":
          description: Note not found
          schema:
            $ref: '#/definitions/handler.Response'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/handler.Response'
      security:
      - ApiKeyAuth: []
      summary: Update the note
      tags:
      - Notes
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
